In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
y2015 = pd.read_csv(
    './data/LoanStats3d-short.csv',
     index_col=0
)

/Users/carl/anaconda/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
y2015.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,68009401,72868139.0,16000.0,16000.0,16000.0,60 months,14.85%,379.39,C,C5,...,0.0,2.0,78.9,0.0,0.0,2.0,298100.0,31329.0,281300.0,13400.0
1,68354783,73244544.0,9600.0,9600.0,9600.0,36 months,7.49%,298.58,A,A4,...,0.0,2.0,100.0,66.7,0.0,0.0,88635.0,55387.0,12500.0,75635.0
2,68466916,73356753.0,25000.0,25000.0,25000.0,36 months,7.49%,777.55,A,A4,...,0.0,0.0,100.0,20.0,0.0,0.0,373572.0,68056.0,38400.0,82117.0
3,68466961,73356799.0,28000.0,28000.0,28000.0,36 months,6.49%,858.05,A,A2,...,0.0,0.0,91.7,22.2,0.0,0.0,304003.0,74920.0,41500.0,42503.0
4,68495092,73384866.0,8650.0,8650.0,8650.0,36 months,19.89%,320.99,E,E3,...,0.0,12.0,100.0,50.0,1.0,0.0,38998.0,18926.0,2750.0,18248.0

In [4]:
# from sklearn import ensemble
# from sklearn.model_selection import cross_val_score

# rfc = ensemble.RandomForestClassifier()
# X = y2015.drop('loan_status', 1)
# Y = y2015['loan_status']
# X = pd.get_dummies(X)

# cross_val_score(rfc, X, Y, cv=5)

In [5]:
# Question what is this select_dtypes selecting? Why didn't we use y2015.columns
categorical = y2015.select_dtypes(include=['object'])
for i in categorical:
    column = categorical[i]
    print(i)
    print(column.nunique())

term
2
int_rate
70
grade
7
sub_grade
35
emp_title
21285
emp_length
12
home_ownership
4
verification_status
3
issue_d
2
loan_status
7
pymnt_plan
1
url
50000
desc
3
purpose
12
title
12
zip_code
856
addr_state
49
earliest_cr_line
605
revol_util
1083
initial_list_status
2
last_pymnt_d
14
next_pymnt_d
3
last_credit_pull_d
15
application_type
2
verification_status_joint
3

In [6]:
# Convert ID and Interest Rate to numeric.
y2015['id'] = pd.to_numeric(y2015['id'], errors='coerce')
y2015['int_rate'] = pd.to_numeric(y2015['int_rate'].str.strip('%'), errors='coerce')

# Drop other columns with many unique variables
y2015.drop(['url', 'emp_title', 'zip_code', 'earliest_cr_line', 'revol_util',
            'sub_grade', 'addr_state', 'desc'], 1, inplace=True)

In [7]:
y2015.tail()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,emp_length,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
49995,65674101,70306867.0,20000.0,20000.0,20000.0,36 months,12.05,664.77,C,7 years,...,0.0,0.0,100.0,100.0,0.0,0.0,42900.0,35060.0,19900.0,20000.0
49996,65344445,69931230.0,8400.0,8400.0,8400.0,36 months,6.89,258.95,A,n/a,...,0.0,4.0,100.0,0.0,1.0,0.0,115035.0,2349.0,20600.0,0.0
49997,65654000,70286779.0,4500.0,4500.0,4500.0,36 months,9.99,145.19,B,10+ years,...,1.0,0.0,86.4,0.0,0.0,0.0,148468.0,16758.0,3800.0,8250.0
49998,65833004,70465761.0,4450.0,4450.0,4400.0,36 months,16.55,157.66,D,n/a,...,0.0,2.0,100.0,83.3,0.0,0.0,538306.0,144633.0,46600.0,157361.0
49999,65724033,70356798.0,14000.0,14000.0,14000.0,60 months,13.18,319.84,C,5 years,...,0.0,1.0,91.7,75.0,1.0,0.0,104179.0,87889.0,8000.0,96179.0

In [8]:
pd.get_dummies(y2015)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,dti,delinq_2yrs,...,last_credit_pull_d_May-2016,last_credit_pull_d_Nov-2015,last_credit_pull_d_Nov-2016,last_credit_pull_d_Oct-2016,last_credit_pull_d_Sep-2016,application_type_INDIVIDUAL,application_type_JOINT,verification_status_joint_Not Verified,verification_status_joint_Source Verified,verification_status_joint_Verified
0,68009401,72868139.0,16000.0,16000.0,16000.0,14.85,379.39,48000.00,33.18,0.0,...,0,0,0,0,0,1,0,0,0,0
1,68354783,73244544.0,9600.0,9600.0,9600.0,7.49,298.58,60000.00,22.44,0.0,...,0,0,0,0,0,1,0,0,0,0
2,68466916,73356753.0,25000.0,25000.0,25000.0,7.49,777.55,109000.00,26.02,0.0,...,0,0,0,0,0,1,0,0,0,0
3,68466961,73356799.0,28000.0,28000.0,28000.0,6.49,858.05,92000.00,21.60,0.0,...,0,0,0,0,0,1,0,0,0,0
4,68495092,73384866.0,8650.0,8650.0,8650.0,19.89,320.99,55000.00,25.49,0.0,...,0,0,0,0,0,1,0,0,0,0
5,68506798,73396623.0,23000.0,23000.0,23000.0,8.49,471.77,64000.00,18.28,0.0,...,0,0,0,0,0,1,0,0,0,0
6,68566886,73456723.0,29900.0,29900.0,29900.0,12.88,678.49,65000.00,21.77,0.0,...,0,0,0,0,0,1,0,0,0,0
7,68577849,73467703.0,18000.0,18000.0,18000.0,11.99,400.31,112000.00,8.68,0.0,...,0,0,0,0,0,1,0,0,0,0
8,66310712,71035433.0,35000.0,35000.0,35000.0,14.85,829.90,110000.00,17.06,0.0,...,0,0,0,0,0,1,0,0,0,0
9,68476807,73366655.0,10400.0,10400.0,10400.0,22.45,289.91,104433.00,25.37,1.0,...,0,0,0,0,0,1,0,0,0,0
10,68341763,72928789.0,20000.0,20000.0,20000.0,10.78,432.66,63000.00,10.78,0.0,...,0,0,0,0,0,0,1,1,0,0
11,68356421,73246236.0,22400.0,22400.0,22400.0,12.88,508.30,95000.00,22.98,0.0,...,0,0,0,0,0,1,0,0,0,0
12,68426545,73316365.0,16000.0,16000.0,16000.0,12.88,363.07,70000.00,26.40,0.0,...,0,0,0,0,0,1,0,0,0,0
13,68407277,73297111.0,3600.0,3600.0,3600.0,13.99,123.03,55000.00,5.91,0.0,...,0,0,0,0,0,1,0,0,0,0
14,68355089,73244858.0,24700.0,24700.0,24700.0,11.99,820.28,65000.00,16.06,1.0,...,1,0,0,0,0,1,0,0,0,0
15,68466926,73356763.0,10000.0,10000.0,10000.0,6.49,306.45,85000.00,13.07,0.0,...,0,0,0,0,0,1,0,0,0,0
16,68338832,73542831.0,1400.0,1400.0,1400.0,12.88,47.10,64000.00,34.95,0.0,...,0,0,0,0,0,1,0,0,0,0
17,68426831,73316657.0,11950.0,11950.0,11950.0,13.44,405.18,34000.00,10.20,0.0,...,0,0,0,0,0,1,0,0,0,0
18,66624733,71350547.0,18000.0,18000.0,18000.0,19.48,471.70,150000.00,9.39,0.0,...,0,0,0,0,0,1,0,0,0,0
19,68616873,73519699.0,8000.0,8000.0,8000.0,11.48,263.74,42000.00,34.80,0.0,...,0,0,0,0,0,1,0,0,0,0
20,67275481,72077199.0,20000.0,20000.0,20000.0,8.49,631.26,85000.00,17.61,1.0,...,0,0,0,0,0,1,0,0,0,0
21,68476668,73366513.0,20000.0,20000.0,20000.0,9.17,637.58,180000.00,14.67,0.0,...,0,0,1,0,0,1,0,0,0,0
22,68476702,73366548.0,28000.0,28000.0,28000.0,13.44,949.38,125000.00,7.49,0.0,...,0,0,0,0,0,1,0,0,0,0
23,68436666,73326493.0,5000.0,5000.0,5000.0,13.44,169.54,79000.00,12.70,0.0,...,0,0,0,0,0,1,0,0,0,0
24,68596180,73485987.0,20000.0,20000.0,20000.0,5.32,602.30,65000.00,18.83,0.0,...,0,0,0,0,0,1,0,0,0,0
25,67849662,72708407.0,4225.0,4225.0,4225.0,14.85,146.16,35000.00,15.22,2.0,...,0,0,0,0,0,1,0,0,0,0
26,68526883,73416719.0,15000.0,15000.0,15000.0,5.32,451.73,44000.00,15.34,0.0,...,0,0,0,0,0,1,0,0,0,0
27,68607141,73509983.0,17600.0,17600.0,17600.0,5.32,530.03,88000.00,26.59,0.0,...,0,0,1,0,0,1,0,0,0,0
28,68476715,73366561.0,6000.0,6000.0,6000.0,7.49,186.61,100000.00,13.28,1.0,...,0,0,0,0,0,1,0,0,0,0
29,67715283,72569997.0,16000.0,16000.0,16000.0,12.88,538.18,65000.00,18.96,0.0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,65261413,69843125.0,20000.0,20000.0,20000.0,14.33,468.80,70000.00,20.12,0.0,...,0,0,0,0,0,1,0,0,0,0
49971,65252237,69833949.0,10500.0,10500.0,10500.0,12.05,233.84,92697.00,9.65,0.0,...,0,0,0,0,0,1,0,0,0,0
49972,65633904,70266676.0,11000.0,11000.0,11000.0,12.59,247.99,28000.00,24.52,0.0,...,0,0,0,0,0,1,0,0,0,0
49973,65603986,70246782.0,15000.0,15000.0,15000.0,9.17,478.19,50000.00,17.59,0.0,...,0,1,0,0,0,1,0,0,0,0
49974,65593952,70226738.0,16800.0,16800.0,16775.0,18.49,431.11,37540.08,22.65,1.0,...,0,0,0,0,0,1,0,0,0,0
49975,65724121,70356889.0,20000.0,20000.0,20000.0,7.89,625.72,74000.00,27.22,1.0,...,0,0,0,0,0,1,0,0,0,0
49976,65733591,70366353.0,17875.0,17875.0,17825.0,19.99,664.21,90000.00,33.20,0.0,...,0,0,0,0,0,1,0,0,0,0
49977,65704083,70336855.0,4000.0,4000.0,4000.0,9.99,129.05,84000.00,25.67,0.0,...,0,0,0,0,0,1,0,0,0,0
49978,65734122,70366899.0,16000.0,16000.0,16000.0,10.99,523.75,45000.00,8.59,0.0,...,0,0,0,0,0,1,0,0,0,0
49979,65814128,70446898.0,6000.0,6000.0,6000.0,9.17,191.28,150000.00,27.77,0.0,...,0,0,0,0,0,1,0,0,0,0
49980,65704081,70336852.0,20000.0,20000.0,20000.0,7.26,619.93,130000.00,20.05,0.0,...,0,0,0,0,0,1,0,0,0,0
49981,65633967,70266739.0,5000.0,5000.0,5000.0,7.26,154.99,46800.00,13.46,0.0,...,0,0,0,0,0,1,0,0,0,0
49982,65803989,70436771.0,14400.0,14400.0,14400.0,16.99,357.80,36000.00,26.77,5.0,...,0,0,0,0,0,1,0,0,0,0
49983,65692227,70324954.0,24350.0,24350.0,24300.0,12.59,815.65,58000.00,17.61,0.0,...,0,0,0,0,0,1,0,0,0,0
49984,65594031,70226823.0,18000.0,18000.0,18000.0,8.18,565.56,70000.00,14.25,0.0,...,0,0,0,0,0,1,0,0,0,0
49985,65724153,70356922.0,9000.0,9000.0,9000.0,9.17,286.92,45000.00,9.01,0.0,...,0,0,0,0,0,1,0,0,0,0
49986,65682283,70315017.0,13200.0,13200.0,13200.0,6.24,403.01,140000.00,12.87,0.0,...,0,0,0,0,0,1,0,0,0,0
49987,65304989,69891818.0,25000.0,25000.0,25000.0,5.32,752.87,175000.00,18.39,0.0,...,0,0,0,0,0,1,0,0,0,0
49988,64691291,69202007.0,12075.0,12075.0,12075.0,16.99,300.03,36000.00,17.90,0.0,...,0,0,0,0,0,1,0,0,0,0
49989,65783852,70416613.0,21525.0,21525.0,21475.0,17.57,541.58,48948.00,31.48,0.0,...,0,0,0,0,0,1,0,0,0,0
49990,65774061,70406844.0,30000.0,30000.0,29950.0,12.59,1004.91,124972.00,11.18,0.0,...,0,0,0,0,0,1,0,0,0,0
49991,65794164,70426935.0,18250.0,18250.0,18250.0,13.18,616.50,36500.00,16.44,0.0,...,0,0,0,0,0,1,0,0,0,0
49992,65744179,70376944.0,8000.0,8000.0,8000.0,10.99,261.88,51000.00,26.80,5.0,...,0,0,0,0,0,1,0,0,0,0
49993,65252177,69833889.0,6000.0,6000.0,6000.0,8.18,188.52,50000.00,27.39,0.0,...,0,0,0,0,0,1,0,0,0,0
49994,65734032,70366805.0,31875.0,31875.0,31800.0,25.99,954.17,83897.00,37.53,0.0,...,0,0,0,0,0,1,0,0,0,0
49995,65674101,70306867.0,20000.0,20000.0,20000.0,12.05,664.77,80000.00,14.39,0.0,...,0,0,0,0,0,1,0,0,0,0
49996,65344445,69931230.0,8400.0,8400.0,8400.0,6.89,258.95,88600.00,2.60,0.0,...,0,0,0,0,0,1,0,0,0,0
49997,65654000,70286779.0,4500.0,4500.0,4500.0,9.99,145.19,75000.00,6.29,1.0,...,0,0,0,0,0,1,0,0,0,0
49998,65833004,70465761.0,4450.0,4450.0,4400.0,16.55,157.66,94300.00,38.22,0.0,...,0,0,0,0,0,1,0,0,0,0
49999,65724033,70356798.0,14000.0,14000.0,14000.0,13.18,319.84,140000.00,13.60,0.0,...,0,0,0,0,0,1,0,0,0,0

In [9]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

rfc = ensemble.RandomForestClassifier()
X = y2015.drop('loan_status', 1)
Y = y2015['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)

cross_val_score(rfc, X, Y, cv=10)

array([ 0.98260696,  0.97880848,  0.97980808,  0.9820036 ,  0.98160368,
        0.9796    ,  0.98039608,  0.98019604,  0.9819964 ,  0.98038038])

In [10]:
from matplotlib.mlab import PCA as mlabPCA
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [11]:
X = y2015.drop('loan_status', 1)
X = pd.get_dummies(X).dropna()
pca = PCA(n_components=3)
pca.fit(X)
PCA(copy=True, iterated_power='auto', n_components=3, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)
print(pca.explained_variance_ratio_)

[ 0.97798116  0.01548648  0.00362734]

In [12]:
rfc = ensemble.RandomForestClassifier()
X = pca
Y = y2015['loan_status']

cross_val_score(rfc, X, Y, cv=10)

TypeError: Singleton array array(PCA(copy=True, iterated_power='auto', n_components=3, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False), dtype=object) cannot be considered a valid collection.